version: "3.8"
services:
  frontend:
    image: frontend:v1
    networks:
      - mynetwork
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    name: star-link
    driver: bridge
